version: "3"

backend-file-manager:
  image: raulglezrdguez/backend-file-manager
  ports:
    - "4000:4000"
  environment:
    - PORT=4000
    - NODE_ENV=development
    - SECRET_KEY=${SECRET_KEY}
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - EMAIL_USER=${EMAIL_USER}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}

    - HOST=${HOST}
