version: "3"

services:
  backend-file-manager:
    deploy: # docker swarm
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s

    build:
      context: . # path to the Dockerfile
      args:
        NODE_ENV: production

    environment:
      - PORT=4000
      - NODE_ENV=production

      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

    # override de CMD command in Dockerfile
    command: node server.js
